version: '3'
services:
  database:
    image: "postgres:latest"
    networks:
      default:
        ipv4_address: 10.10.10.100
    volumes:
      - "./database:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DATABASE: "postgres"
  backend:
    image: "backend"
    networks:
      default:
        ipv4_address: 10.10.10.200
    ports:
      - "8080:8080"
    depends_on:
      - database
  frontend:
    image: "frontend"
    ports:
      - "80:80"


networks:
  default:
    ipam:
      config:
        - subnet: "10.10.10.0/24"
          gateway: "10.10.10.1"